##################################################
### VARIABLES
##################################################
@host=http://localhost:8081
@projectId=

##################################################
### EARNED VALUE
##################################################

GET {{host}}/api/projects/{{projectId}}/earned-value