##################################################
### VARIABLES
##################################################
@host=http://localhost:8081
@userId=c5450138-aae9-41be-8768-fe28f1043779
@projectId=9f0268b5-8efd-42ff-8974-3826ed8898ae

##################################################
### CREATE
##################################################

POST {{host}}/api/projects
Content-Type: application/json

{
    "userId":"{{userId}}",
    "name":"Sistema ERP",
    "description":"Proyecto principal",
    "startDate":"2026-06-01",
    "endDate":"2026-12-31",
    "status":"PLANNED"
}

###

##################################################
### FIND ALL
##################################################

GET {{host}}/api/projects

###

##################################################
### FIND BY ID
##################################################

GET {{host}}/api/projects/{{projectId}}

###

##################################################
### UPDATE
##################################################

PUT {{host}}/api/projects/{{projectId}}
Content-Type: application/json

{
    "userId":"{{userId}}",
    "name":"Sistema ERP V2",
    "description":"Proyecto actualizado",
    "startDate":"2026-06-01",
    "endDate":"2026-12-31",
    "status":"IN_PROGRESS"
}

###

##################################################
### DELETE
##################################################

DELETE {{host}}/api/projects/{{projectId}}

###

##################################################
### NEGATIVE TESTS
##################################################

GET {{host}}/api/projects/00000000-0000-0000-0000-000000000000