/**
 * Project Management REST API
 *
 * Contact: abraham@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request used to create or update activities.
 */
export interface ActivityRequest { 
    /**
     * The name of the activity
     */
    name: string;
    /**
     * The ID of the project to which the activity belongs
     */
    projectId: string;
    /**
     * The budget at completion for the activity
     */
    budgetAtCompletion: number;
    /**
     * The planned percentage for the activity
     */
    plannedPercentage: number;
    /**
     * The actual percentage for the activity
     */
    actualPercentage: number;
    /**
     * The actual cost for the activity
     */
    actualCost: number;
}

