/**
 * Project Management REST API
 *
 * Contact: abraham@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response containing activity details.
 */
export interface ActivityResponse { 
    id?: string;
    projectId?: string;
    name?: string;
    budgetAtCompletion?: number;
    plannedPercentage?: number;
    actualPercentage?: number;
    actualCost?: number;
    createdAt?: string;
    updatedAt?: string;
}

