/**
 * Project Management REST API
 *
 * Contact: abraham@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Earned Value Management metrics.
 */
export interface MetricsResponse { 
    /**
     * The planned value of the project
     */
    pv?: number;
    /**
     * The earned value of the project
     */
    ev?: number;
    /**
     * The cost variance of the project
     */
    cv?: number;
    /**
     * The schedule variance of the project
     */
    sv?: number;
    /**
     * The cost performance index of the project
     */
    cpi?: number;
    /**
     * The schedule performance index of the project
     */
    spi?: number;
    /**
     * The estimate at completion of the project
     */
    eac?: number;
    /**
     * The variance at completion of the project
     */
    vac?: number;
    /**
     * The cost status of the project
     */
    costStatus?: MetricsResponse.CostStatusEnum;
    /**
     * The schedule status of the project
     */
    scheduleStatus?: MetricsResponse.ScheduleStatusEnum;
    /**
     * The interpretation of the cost status
     */
    costInterpretation?: string;
    /**
     * The interpretation of the schedule status
     */
    scheduleInterpretation?: string;
}
export namespace MetricsResponse {
    export const CostStatusEnum = {
        UnderBudget: 'UNDER_BUDGET',
        OverBudget: 'OVER_BUDGET',
        OnBudget: 'ON_BUDGET'
    } as const;
    export type CostStatusEnum = typeof CostStatusEnum[keyof typeof CostStatusEnum];
    export const ScheduleStatusEnum = {
        AheadOfSchedule: 'AHEAD_OF_SCHEDULE',
        BehindSchedule: 'BEHIND_SCHEDULE',
        OnSchedule: 'ON_SCHEDULE'
    } as const;
    export type ScheduleStatusEnum = typeof ScheduleStatusEnum[keyof typeof ScheduleStatusEnum];
}


