/**
 * Project Management REST API
 *
 * Contact: abraham@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectResponse { 
    id?: string;
    name?: string;
    description?: string;
    startDate?: string;
    endDate?: string;
    status?: ProjectResponse.StatusEnum;
}
export namespace ProjectResponse {
    export const StatusEnum = {
        Planned: 'PLANNED',
        InProgress: 'IN_PROGRESS',
        Completed: 'COMPLETED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


