/**
 * Project Management REST API
 *
 * Contact: abraham@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request used to create or update projects.
 */
export interface ProjectRequest { 
    /**
     * The ID of the user who owns the project
     */
    userId: string;
    /**
     * The name of the project
     */
    name: string;
    /**
     * The description of the project
     */
    description?: string;
    /**
     * The start date of the project
     */
    startDate?: string;
    /**
     * The end date of the project
     */
    endDate?: string;
    /**
     * The status of the project
     */
    status: ProjectRequest.StatusEnum;
}
export namespace ProjectRequest {
    export const StatusEnum = {
        Planned: 'PLANNED',
        InProgress: 'IN_PROGRESS',
        Completed: 'COMPLETED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


