/**
 * Project Management REST API
 *
 * Contact: abraham@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response containing user details with information returned by the API.
 */
export interface UserResponse { 
    /**
     * The unique identifier of the user
     */
    id?: string;
    /**
     * The first name of the user
     */
    firstName?: string;
    /**
     * The last name of the user
     */
    lastName?: string;
    /**
     * The email address of the user
     */
    email?: string;
    /**
     * Indicates if the user is enabled
     */
    enabled?: boolean;
    /**
     * The date and time when the user was created
     */
    createdAt?: string;
    /**
     * The date and time when the user was last updated
     */
    updatedAt?: string;
}

