### Crear usuario

POST http://localhost:8081/api/users
Content-Type: application/json

{
  "firstName": "Abraham",
  "lastName": "Ramirez",
  "email": "abraham@test.com",
  "password": "12345678"
}

###

GET http://localhost:8081/api/users